### ISSUE TITLE
Expose pipeable apis for Ref like modules

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/effect#1305]
To be perfectly in line with `fp-ts` standard and avoiding awkward discoveries we should expose a pipeable API for every module

**Comment by mattiamanzati** [comment]
Ok, so I dont promise anything here until I have a working PoC, but ideally we could build something that behaves in this way:

Given Effect or effect-built packages will also ship a .json file with the tsplus annotations in a standard location or even inside the package.json, and the user has installed @effect/language-service

When the user types "ref.", the language service will get the tsplus tag type of the type at the location. The language service should be able to inject additional completion items, based on the Effect tsplus.json items that are companion object methods of the type at location.

Expect that instead of just pushing the method name, the language service will return the required edits to the editor in order to add the pipe around (if necessary) and instead of just writing the method name in the editor, will write "Ref.update()" and place the caret inside the parenthesis.

I need to give this a shot, will require the .json due to performance reasons (also to avoid duplication of logic already present in tsplus).
