### ISSUE TITLE
Duration parser for Options in effect/cli, like config in effect

### ISSUE THREAD

**Issue by joepjoosten** [Effect-TS/effect#2484]
### What is the problem this feature would solve?

Must write our own parser to parse a duration option

### What is the feature you are proposing to solve the problem?

Easier to pass Duration option to cli app. This can be like the parser for Config<Duration.Duration>

https://github.com/Effect-TS/effect/blob/a4032fac1d36b7d37773d72f0c8a57f74b9b31a9/packages/effect/src/internal/config.ts#L293-L299

### What alternatives have you considered?

Write your own parser. But when Config has it, why not Options in effect/cli

**Comment by joepjoosten** [comment]
A more general question: Options in effect/cli is "closely" related to Options, of is a subset / intersection of the Config methods? Is it possible to reuse this subset / intersection?

**Comment by mikearnaldi** [comment]
They don't look related imho, Config is a description of a configuration to be read from a ConfigProvider, Options in CLI represent options that the user can pass through cli flags

**Comment by IMax153** [comment]
@joepjoosten - as @mikearnaldi mentioned, I'm not seeing the parallel between Config and Options. They are two totally separate data types used for different purposes. 

Are you looking for a way to parse a duration input from the command line?

**Comment by joepjoosten** [comment]
@mikearnaldi @IMax153 Good point. 

What i noticed when i was writing Options for my CLI was the following
```
Options.text("optionA").pipe(Options.optional, Options.withDescription('Option A.'), Options.withFallbackConfig(Config.string("OPTION_A").pipe(Config.option))
```
That's why it seemed related (in one direction Config -> Options)

I saw the "inconsistancy" between e.g. Options.optional <=> Config.option, and that Options is lacking the recently added Config.duration.

Maybe the Options are a ConfigProvider in a way?

**Comment by IMax153** [comment]
Hey @joepjoosten - I think I'm understanding a bit better now.

First of all, let me clear up that `Options` is not analagous to a `ConfigProvider` whatsoever.

`Options` *uses* the `ConfigProvider` to allow the CLI program to fall back to the specified `Config` value when the command-line flag is not provided. So in a situation where `optionA` is not provided by the user, it can fall back to the specified `Config` value, which will be read using whichever `ConfigProvider` is provided to the program. The default `ConfigProvider` reads from the environment, so if no `ConfigProvider` is provided by you in your CLI program the default behavior will be to fall back to the value in the environment (if present).

Also, looking at your sample above, I would adjust the code as follows:
```ts
Options.text("optionA").pipe(
  Options.withDescription('Option A.'), 
  Options.withFallbackConfig(Config.string("OPTION_A")),
  Options.optional
)
```
which moves the `Options.optional` to the end of the pipeline and removes the `Config.option`.

This will result in the following behavior when the `optionA` command-line option attempts to be parsed:
1. Read the command-line and use the specified value, if present, returning `Option.some(value)`
2. If not, try reading from the environment and use that value, if present, returning `Option.some(value)`
3. If not, return `Option.none`

The way you wrote `optionA` previously, you would never attempt to use the fallback config value since `Options.optional` would just return `Option.none` if the command-line value wasn't there.

**Comment by IMax153** [comment]
Also, regarding parsing a duration from the command line, you could just do:
```ts
import * as Options from "@effect/cli/Options"
import * as Duration from "effect/Duration"
import * as Option from "effect/Option"

const myOption = Options.text("optionA").pipe(
  Options.withDescription('Option A.'), 
  Options.withFallbackConfig(Config.string("OPTION_A")),
  Options.optional,
  Options.map(Option.flatMap(Duration.decodeUnknown))
)
```
**Note**: I did not test this code in an editor, you might need to adjust slightly.

**Comment by joepjoosten** [comment]
Great answer! solves my questions.
