### ISSUE TITLE
Idea: Schema variants

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/effect#3215]
### What is the problem this feature would solve?

It's common to want to define many "variants" of the same schema, for example, when working with database tables it's common to want to define Select, Insert, and Update schemas. Being able to define these all at once instead of first defining a schema and then manipulating it to create it's derivatives would be convenient.

### What is the feature you are proposing to solve the problem?

 [effect-kysely](https://www.npmjs.com/package/effect-kysely) employs a similar concept but the idea can be useful in other contexts as well. 

Something like: 

```ts
const { Update, Insert } = makeVariants({
  all: Schema.String, // included in all variants
  
  allWithOverrides: variant(Schema.Number, { // included in all variants but changes in some variants
    Update: Schema.String,
  }),
  
  some: variant({ // no default, only included in specified variants
    Insert: Schema.String
  })

});
```

**Comment by datner** [comment]
Hmm I feel like this would be more appropriate of a higher-level package (`@effect/entities`? idk lol) as it has specific semantics that are confusing when combined with schemas without any context: (Select, Insert, Update) * (Encoded, Constructor, Type). Especially since they have a nearly full overlap in many cases.
Theres also the issue that it's not clear how variants would work with all the other elements in schema like `TaggedClass`.
This feels like a desire to get the same ergonomics as [`@nestjs/mapped-types`](https://trilon.io/blog/introducing-mapped-types-for-nestjs), despite them already existing in schema

Its also debatable how more useful it is over not using it...
```ts
const Update = Schema.String
const Insert = Schema.String
```

In the context of kysely it makes sense for wanting to mimic the source lib, but as a general util it's less-so.

**Comment by jessekelly881** [comment]
@datner Hmm. You're probably right. I was initially thinking that it would make sense to add a schema helper to /sql specifically for tables. That might make more sense than adding a general helper.

**Comment by datner** [comment]
@jessekelly881 /sql already has a module for schemas, maybe it can it in there?
