### ISSUE TITLE
Deferred.succeed allows value parameter to be omitted

### ISSUE THREAD

**Issue by dmeehan1968** [Effect-TS/effect#3878]
### What version of Effect is running?

3.10.8

### What steps can reproduce the bug?

```ts
Deferred.make<string>().pipe(
  Effect.tap(def => Deferred.succeed(def))
)
```

### What is the expected behavior?

```ts
Deferred.make<string>().pipe(
  Effect.tap(def => Deferred.succeed(def))
                                  // ^ expected 2 arguments, 1 provided,
)
```

### What do you see instead?

No IDE errors reported, when hovering over `succeed` its type is shown as:

```
function <Deferred<string, never>>(value: any): <E>(self: Deferred<Deferred<string, never>, E>) => Effect.Effect<boolean>
```

### Additional information

I'm new to Effect and so might well be missing something, but was following [this example](https://rlee.dev/practical-use-cases-for-effect-ts-polling-ai-apis) and happened to omit the `url` parameter in the `Deferred.succeed`.

The outcome was that the forked fibre appeared to never complete (the client query was repeated after the interval) until the unit test I was running it in timed out.  It took me a while to locate the error, because there was no static warning that the parameter was omitted.  I would definitely have expected `succeed` to only be value with a string, as typed.

**Comment by KhraksMamtsov** [comment]
I agree that this behaviour is not expected

As a workaround, in order to make this function more strict, you can pass `{ onlyEffect: true }` setting to the second argument.

**Comment by dmeehan1968** [comment]
@KhraksMamtsov Can you explain which second argument you are referring too, as neither Deferred.make or Deferred.succeed appear to have options.

The `Deferred<Deferred<string, never>, E>` seems very odd as the self argument type.

**Comment by KhraksMamtsov** [comment]
Effect.tap

**Comment by gcanti** [comment]
@dmeehan1968 the long explanation is as follows:

`Effect.tap` has an overload with the following signature:

```ts
<A, X>(f: (a: NoInfer<A>) => X): <E, R>(
  self: Effect<A, E, R>
) => [X] extends [Effect<infer _A1, infer E1, infer R1>] ? Effect<A, E | E1, R | R1>
  : [X] extends [PromiseLike<infer _A1>] ? Effect<A, E | Cause.UnknownException, R>
  : Effect<A, E, R>
```

In your case, it is interpreted as:

```ts
<A, X>(f: (a: NoInfer<A>) => X): <E, R>(
  self: Effect<A, E, R>
) => Effect<A, E, R>
```

since you are returning `Deferred.succeed(def)`, which is neither an `Effect` nor a `PromiseLike`.

Therefore, what you return is valid (i.e., there is no type error) but is ignored. So, this behavior is not a bug.

If you change the code to:

```ts
import { Deferred, Effect } from "effect"

const program = Deferred.make<string>().pipe(
  Effect.tap((def) => Deferred.succeed(def), { onlyEffect: true })
)
```

then you get a type error because the `{ onlyEffect: true }` option enforces returning an `Effect`, which `Deferred.succeed(def)` is not.

**Comment by dmeehan1968** [comment]
@gcanti Thanks for the detail explanation, but this seems to miss the original point.

The bug appears to be in the `Deferred.succeed` not showing a type error on the missing second argument.   The `tap` in the sample was the simplest illustration I could easily come up with, consistent with the original source (as `Deferred.make` produces an Effect so needs unwrapping - not sure if that's the correct terminology).  

I provided a link to the example where I got the usage from, which may of course not be correct, but as Effect-ts claims to leverage type safety to write correct code, I would have expected it to do a better job of telling me I'm using it wrong, whether in the `Effect.tap` or `Deferred.succeed` usage.  I ended up with a runtime error, the source of which was hard to find.

I was under the impression that `Effect.tap` has no affect on the value passed on, so I'm struggling to see why it even cares about the return value (other than as a convenience as typing it as void would make concise usage in arrow functions more problematic).

**Comment by KhraksMamtsov** [comment]
The error is not in `Deferred.succeed`, because many functions in Effect support a digital signature (https://effect.website/docs/code-style/dual ). This is the expected behavior

Unfortunately, a type-safe program does not always work as the author expects.

Specifically, in this function (`Effect.tap`), a certain deviation from strictness is allowed for the sake of interoperability with native `Promise` and ease of use.   Which, however, can be made more strict with the appropriate option.

**Comment by dmeehan1968** [comment]
@KhraksMamtsov Aah yes, I see why the param can be omitted when used in this way.  Thank you.
