### ISSUE TITLE
@effect/rpc. I have not seen such a terrible syntax yet

### ISSUE THREAD

**Issue by MrOxMasTer** [Effect-TS/effect#3950]
### What is the problem this feature would solve?

come up with a normal syntax

### What is the feature you are proposing to solve the problem?

come up with a normal syntax

### What alternatives have you considered?

You know, I actually liked Effect, but after seeing the rpc syntax - I was just shocked. Trpc is not quite perfectly compatible with Effect and in some moments. I was really excited when I saw that there was a @effect/rpc package, but after seeing the syntax I saw, my desire dropped to zero to use it and I'm not surprised that this package has 1.5k downloads and they're all dropping.
With my whole dislike for java - Spring and nest.js are still ok compared to this syntax. 
At first I was just killed by the syntax of error generation, but I put up with it, with this `TaggerError` through classes, yes also that it does not allow to extend already existing errors, which are already in the libraries of various, but this:
For each request to generate its own class, to write 3 times the same thing. Also to call a query, to create an instance of class 🤮🤮🤮🤮
![image](https://github.com/user-attachments/assets/19400c44-6029-495b-96ce-c581769d7385)
![image](https://github.com/user-attachments/assets/e10f3b81-1261-4019-af6d-564e425e2b19)

So much of this syntax is unreadable that I didn't even realize what was going on here at all at first. Forget about this `extends` syntax in classes everywhere, otherwise nobody will really use it. When the whole js community is striving more towards a functional syntax like the world in general, in the form of abandoning monoliths in java, converting from java to kotlin, React from classes to functions, you decide to add classes where you just don't need to.
I don't understand how after the wonderful pipe function and such a linear functional syntax the desire to create this in such a way was born....

**Comment by IMax153** [comment]
@MrOxMasTer - we certainly appreciate the feedback. We also acknowledge that there is a bit of verbosity when defining the domain model for your RPCs. However, we don't really believe that utilizing a class-based approach for domain modeling results in non functional code. In addition, you are free to use either the `Effect.gen`-based generator syntax _or_ the `pipe`-based syntax - we expose both to allow developers the choice of writing code in the way that they prefer.

We also do have several good reasons we have leaned into a class-based route for domain modeling in Effect. 

Some of the benefits of using classes for domain models include:
- Having a single, opaque identifier to represent both the type and the piece of data
- Allows access to both:
  - the static side of the class (i.e. for constructors as well as representing the schema) 
  - the instance side of the class for exposing getters and helper methods
- Allows the class itself to be safely serializable/deserializable since the class instance is also a schema

All the above being said, the `@effect/rpc` package is still very much considered "unstable" as we are still iterating on it. 

If you have any additional feedback, please feel free to share it here. We take all feedback we receive from users into consideration when designing our APIs.

**Comment by MrOxMasTer** [comment]
> Some of the benefits of using classes for domain models include:
> 
> * Having a single, opaque identifier to represent both the type and the piece of data
> * Allows access to both: 
>   * the static side of the class (i.e. for constructors as well as representing the schema)
>   * the instance side of the class for exposing getters and helper methods
> * Allows the class itself to be safely serializable/deserializable since the class instance is also a schema

It looks like a boilerplate of code and constructors in your classes, nothing is literally being used out of all those benefits (except under the hood only), only it makes DX terrible:
![image](https://github.com/user-attachments/assets/1d39fe07-82ed-4898-93ff-95c88def330e)

I think schemes for failure and success, you can write without classes, and this boilerplate of code trash:
![image](https://github.com/user-attachments/assets/9ab9a3f0-e23f-4958-939d-eb76048fa95d)
![image](https://github.com/user-attachments/assets/ac8ed4f8-144b-4bf8-a599-68e6fce99a82)

it's already unpleasant

Why couldn't syntax like this be done?:
```ts
const procedure = Effect.procedure(<inputSchema>, <outputSchema>, () => {...})
```
as in trpc, it's clear that you were inspired by this library:
well, or this syntax?:
```ts
const req = Request.base(<inputSchema>, <outSchema>, () => {...})
```

**Comment by mikearnaldi** [comment]
very hard to see anything positive come out of this way of discussing the argument. Feel free to open more actionable feedback issues taking into account basic rules of respect.
