### ISSUE TITLE
Allow Effect.annotateLogs to be used inside generator/effect to annotate current effect

### ISSUE THREAD

**Issue by florianbepunkt** [Effect-TS/effect#4018]
### What is the problem this feature would solve?

We have some AWS Lambda functions in a multi-tenant env, where we would like to annotate logs inside a gen:

```typescript
const program = (event: EventBridgeEvent<typeof Client.Events.HardDeleted>) =>
  Effect.gen(function* () {
    const { streamId: clientId } = event.detail;
    const tenantId = event.detail.payload.tenantId;
    // yield * Effect.annotateLogs({ clientId, tenantId }); // <-- would like to do this
    const productRepository = yield* ProductRepository;
    yield* productRepository.deleteByClientId(clientId);
  });
```

### What is the feature you are proposing to solve the problem?

Currently Effect.annotateLogs can only wrap an effect. It would be great to allow it to add annotations to the current effect where it is called from.

**Comment by IMax153** [comment]
@florianbepunkt - you can use `Effect.annotateLogsScoped` for this ([see api docs](https://effect-ts.github.io/effect/effect/Effect.ts.html#annotatelogsscoped)). 

Note that it's not really possible to have a non-scoped variant that does the same because it isn't possible to attach the log annotations to the "current effect" in this manner. We need to be able to track where the annotations are applied vs where they are not. With the scoped variant, we can apply the annotations to all logs that occur within the scoped region.

**Comment by florianbepunkt** [comment]
@IMax153 Scope make perfect sense. Overlooked this variant in the docs. Thank you.
